/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface AddUserInput
 */
export interface AddUserInput {
    /**
     * 用户名
     * @type {string}
     * @memberof AddUserInput
     */
    account: string;
    /**
     * 姓名
     * @type {string}
     * @memberof AddUserInput
     */
    name: string;
    /**
     * 
     * @type {Gender}
     * @memberof AddUserInput
     */
    gender?: Gender;
    /**
     * 组织机构id
     * @type {number}
     * @memberof AddUserInput
     */
    orgId?: number;
    /**
     * 昵称
     * @type {string}
     * @memberof AddUserInput
     */
    nickName?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof AddUserInput
     */
    birthday?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof AddUserInput
     */
    mobile?: string | null;
    /**
     * 邮箱
     * @type {string}
     * @memberof AddUserInput
     */
    email?: string | null;
    /**
     * 备注
     * @type {string}
     * @memberof AddUserInput
     */
    remark?: string | null;
    /**
     * 角色
     * @type {Array<number>}
     * @memberof AddUserInput
     */
    roles?: Array<number> | null;
}
